### ISSUE TITLE
L1 private key

### ISSUE THREAD

**Issue by mesowea** [base-org/withdrawer#1]
Hello! I wonder whether it is possible to prove and finalize the withdrawal from the other account (not the one that sent the funds to 0x420...010
Please state this in the guide
Thank you

**Comment by mesowea** [comment]
UPD: tested everything on eth and base goerli, the L1 account (which private key is passed after the flag --private-key) may be ANY account that has enough ETH

**Comment by mdehoog** [comment]
Yes that is correct. Good point, will add to the README.
