### ISSUE TITLE
Fault Proofs Support

### ISSUE THREAD

**Issue by tynes** [base-org/withdrawer#15]
The API for doing a withdrawal is changing with the release of fault proofs. The modifications to the bridge can be found in the [specs](https://github.com/ethereum-optimism/specs/blob/08d3c7189309e9e739d11312ed2ac7c1a43cb582/specs/experimental/fault-proof/stage-one/bridge-integration.md). This tool will need to be updated to support fault proof style withdrawals if it is used in production.

**Comment by wbnns** [comment]
@tynes

Thanks for tracking and opening this, Mark.  👍 🤝
