### ISSUE TITLE
Can't prove withdrawal after 14 days.

### ISSUE THREAD

**Issue by mehteflon** [base-org/withdrawer#7]
Hey there,

When trying to prove my withdrawal, I send this command:

withdrawer --network base-mainnet --withdrawal 0xefce5b34d7b6262a277774896cff42ce8f4da6a5049aafd8d38ebfac9368eb66 --rpc https://rpc.flashbots.net/ --private-key <L1 private key>

And I am returned the following:

Error completing withdrawal: withdrawal tx 0xefce5b34d7b6262a277774896cff42ce8f4da6a5049aafd8d38ebfac9368eb66 was included in L2 block 2034109 (time 1690857565) but L1 only knows of L2 proposal 2628000 (time 1692045347) at head 604800 (time 17915639) which has not reached output confirmation yet (period is 1692046919).

I think there is a bug somewhere in withdrawer ?

Thank you in advance for your help.

**Comment by mesowea** [comment]
yes, there is possibly a bug
I did everything manually

1. Open your _'proveWithdrawalTransaction'_ tx: https://etherscan.io/tx/0xce3338873512243035d09d4825844a02d7e6839ee17d3cb14ace0e3a4f0b3f00
2. Look for the "Input Data:" on the page from **1.** and click on _"Decode Input Data"_. You need the parts of the data starting with _"_tx"_:

_tx.nonce | uint256 | **1766847064778384329583297500742918515827483896875618958121606201292619848**
-- | -- | --
0 | _tx.sender | address | **0x4200000000000000000000000000000000000007**
0 | _tx.target | address | **0x866E82a600A1414e583f7F13623F1aC5d58b0Afa**
0 | _tx.value | uint256 | **2000000000000000**
0 | _tx.gasLimit | uint256 | **490798**
0 | _tx.data | bytes | **0xd764ad0b000100000000000000000000000000000000000000000000000000000000004300000000000000000000000042000000000000000000000000000000000000100000000000000000000000003154cf16ccdb4c6d922629664174b904d80f2c3500000000000000000000000000000000000000000000000000071afd498d00000000000000000000000000000000000000000000000000000000000000030d4000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000000a41635f5fd000000000000000000000000a895330bca4ecaa324b3b11c1e14e6823addcc6c000000000000000000000000a895330bca4ecaa324b3b11c1e14e6823addcc6c00000000000000000000000000000000000000000000000000071afd498d00000000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000**

4. Open the Base bridge contract link on explorer: https://etherscan.io/address/0x49048044d57e1c92a77f79988d21fa8faf74e97e#writeProxyContract
5. Connect your wallet and navigate to "finalizeWithdrawalTransaction (0x8c3152e9)"
6. Then just fill in the correspoding data from **2.** and click **"Write"**
7...
8. PROFIT!

**Comment by mesowea** [comment]
do the same with your another withdrawal after ~1 day
I also you the Rabby wallet which simulates the transaction first. it helps me when I am not sure whether the tx would revert
Hope it helped

**Comment by mehteflon** [comment]
Thank you for looking into this! Your solution worked for 2 of my withdrawals, but there is a third that I can't seem to resolve. It says "ready for relay" but I can't see the "proved withdrawal" transaction on etherscan. Here is the basechain tx: 0xefce5b34d7b6262a277774896cff42ce8f4da6a5049aafd8d38ebfac9368eb66. Can you look at this one?

**Comment by mehteflon** [comment]
bump

**Comment by mesowea** [comment]
> bump

hey, I believe you didn't send the "provewithdrawal" tx

**Comment by mesowea** [comment]
![image](https://github.com/base-org/withdrawer/assets/72040182/013b36b8-e1f5-4626-88af-ade86614a005)
yeah. only two here

> Thank you for looking into this! Your solution worked for 2 of my withdrawals, but there is a third that I can't seem to resolve. It says "ready for relay" but I can't see the "proved withdrawal" transaction on etherscan. Here is the basechain tx: 0xefce5b34d7b6262a277774896cff42ce8f4da6a5049aafd8d38ebfac9368eb66. Can you look at this one?

**Comment by mesowea** [comment]
send the provewithdrawal, then wait for 7+ days and finalize the withdrawal. Good luck bro
Anyway there is an official bridge live now, why u use the scripts on github? :)

**Comment by mehteflon** [comment]
I tried to use the official bridge, but my withdrawal for 1.1 ETH is not showing up on the website. Also, when I send the prove withdrawal command in CLI, I get an error. Hopefully devs notice this

**Comment by mesowea** [comment]
> I tried to use the official bridge, but my withdrawal for 1.1 ETH is not showing up on the website. Also, when I send the prove withdrawal command in CLI, I get an error. Hopefully devs notice this

let me try to help you. please, share the error you get

**Comment by mehteflon** [comment]
C:\Users\willk>withdrawer --network base-mainnet --withdrawal 0xefce5b34d7b6262a277774896cff42ce8f4da6a5049aafd8d38ebfac9368eb66 --rpc https://rpc.flashbots.net --private-key <private key> Error completing withdrawal: withdrawal tx 0xefce5b34d7b6262a277774896cff42ce8f4da6a5049aafd8d38ebfac9368eb66 was included in L2 block 2034109 (time 1690857565) but L1 only knows of L2 proposal 3234600 (time 1693258547) at head 604800 (time 18016007) which has not reached output confirmation yet (period is 1693260371)

**Comment by mesowea** [comment]
did you try using another rpc? just a guess

**Comment by mehteflon** [comment]
Yeah tried like 5 diff ones

**Comment by mehteflon** [comment]
@taycaldwell @mdehoog Any ideas?

**Comment by mehteflon** [comment]
bump @taycaldwell @mdehoog

**Comment by mdehoog** [comment]
@mehteflon just checking, have you installed the latest version?
```
go install github.com/base-org/withdrawer@latest
```
there was a bug in the timing calculation which was fixed with 72d9fe94c317010f27257ba31e494c378c3f5eef, and your logs seem to be indicating the older version

**Comment by mehteflon** [comment]
Duh. Sorry for wasting your time and thank you for helping me! Can't believe I forgot to update.

Cheers.
